# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='collaborate_in',
            field=models.CharField(choices=[('SONG', 'Tema'), ('MUSICAL_GROUP', 'Grupo Musical'), ('PLAYLIST', 'Playlist')], default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('SENT', 'Enviado'), ('PENDING', 'Pendiente'), ('ACEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default=('SENT', 'Enviado'), max_length=8),
        ),
    ]
