# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablespace',
            name='current_size_bite',
            field=models.IntegerField(default=0),
        ),
    ]
